#Name and Port of Application
spring.application.name=AdmissionEnquiryLayer
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


##DataBase properties
#spring.datasource.url=jdbc:mysql://vartman-recovery-db.cjw86ikwsiyk.ap-south-1.rds.amazonaws.com:3306/vartman?ServerTimezone=UTC
#spring.datasource.username=admin
#spring.datasource.password=vartmannirnay-pjsofttech
## SSL configuration
#server.port=14443
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=/etc/letsencrypt/live/fasthire.in/keystore.p12
#server.ssl.key-store-password=123456
#server.ssl.key-alias=fasthire
#server.ssl.enabled=true


server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/fasthireenquiry
spring.datasource.username=root
spring.datasource.password=root

#hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#security properties
jwt.secret=w8hC29uD!s7xKdP#4zLh92VNbgO1tYqA
jwt.expiration=86400000